package com.cafe.modelo.enums;


public enum TipoAuxiliarMaquinas {
	
	/* ---------------------------------*/
	/* tipos de maquinas   */
	/* ---------------------------------*/
	ABANADOR_CEREAL(10,5),
	ADUBADORA_AUTOPROPELIDA(10,20),
	APLICADOR_AUTOPROPELIDO(10,20),
	ATOMIZADOR_COSTAL_MOTORIZADO(8,5),
	CAMINHÃO(10,25),
	COLHEDORA_AUTOMOTRIZ_CAFE(10,0), // n tem na tabela
	COLHEDORA_CAFE(10,0), // n tem na tabela
	DERRIÇADORA(10,0), // n tem na tabela
	MICROTRATOR(10,25),
	MOTO_SERRA(10,25),
	MOTORROÇADEIRA(10,25),
	PA_CARREGADEIRA(10,25),
	PULVERIZADOR(10,20),
	ROÇADEIRA_MANUAL(8,5),
	SOPRADOR(5,5),
	TRATOR(10,20),
	TRATOR_DE_RODA_PEQUENO_PORTE(10,25),
	TRITURADOR(12,5),
	OUTROS(0,0),

	
	/* ---------------------------------*/
	/* tipos de implementos   */
	/* ---------------------------------*/
	ABASTECEDOR_FERTILIZANTES(8,0),
	ABASTECEDOR_PULVERIZADOR(15,5),
	ADUBADEIRA_CITROS_CAFE(10,5),
	ADUBADEIRA_MANUAL(3,0),
	APLICADOR_ADUBO(10,0 ), // n tem na tabela
	APLICADOR_INSETICIDA(12,5),
	APLICADOR_LOCALIZADO_FERTILIZANTES(10,5),
	ARADO(15,5),
	ARADO_AIVECA(15,0),
	BARRA_APLICADORA_HERBICIDA(8,0), // n tem na tabela
	BOMBA_IRRIGAÇÃO(5,5),
	CAPINADEIRA(12,5),
	CARRETA_AGRICOLA(15,5),
	CARRETA_BASCULANTE_CAFE(15,5),
	CARRETA_BASCULANTE_METALICA(15,5),
	CARRETA_BASCULANTE_METALICA_MEDIO_PORTE(15,5),
	CARRETA_DISTRIBUIDORA_FERTILIZANTE_CALCARIO_ADUBO(10,5),
	CARRETA_PULVERIZADORA(8,5),
	//COLHEDORA_CAFE,
	COLHEDORA_CAFE_AUTOMOTRIZ(10,25),
	CULTIVADOR(12,5),
	CULTIVADOR_SUBSOLADOR(12,5),
	DECOTADEIRA_RECEPADEIRA(12,5),
	DISTRIBUIDOR_ADUBO_ORGANICO_CALCARIO(10,5),
	DISTRIBUIDOR_ADUBO_ORGANICO_LIQUIDO(15,5),
	DISTRIBUIDOR_FERTILIZANTE(10,5),
	DISTRIBUIDOR_FERTILIZANTE_CALCARIO(10,5),
	DISTRIBUIDOR_FERTILIZANTE_CORRETIVO(10,5),
	DISTRIBUIDOR_FERTILIZANTE_DISCO(10,5),
	DISTRIBUIDOR_FERTILIZANTE_SOLIDO(10,5),
	DISTRIBUIDOR_FERTILIZANTES_ORGANICOS(10,5),
	ENLEIRADEIRA_GRAO_CAFE(10,25),
	ENXADA_ROTATIVA(12,5),
	ENXADA_ROTATIVA_MEXEDOR_CAMA_AVIARIO(12,5),
	GRADE_ARADORA(15,5),
	GRADE_ARADORA_ARRASTO(15,5),
	GRADE_ARADORA_MECANICA(15,5),
	GRADE_NIVELADORA(15,5),
	GUINCHO_AGRICOLA(12,5),
	GUINCHO_AGRICOLA_TRASEIRO_REBOCAVEL(12,5),
	GUINCHO_BAG(12,5),
	GUINCHO_HIDRAULICO(12,5),
	GUINCHO_TRASEIRO(12,5),
	INCORPORADOR_FERTILIZANTE(10,5),
	LAMINA_ENLEIRADORA(15,25),
	MANEJO_SOLO_TRITURADOR(12,5),
	//PA_CARREGADEIRA,
	PA_CARREGADEIRA_TRASEIRA(12,5),
	PLANTADEIRA_ADUBADEIRA(15,20),
	PLANTADEIRA_CAFE(15,5),
	PLATAFORMA(10,25),
	PODADEIRA(12,5),
	PODADEIRA_HIDRAULICA(12,5),
	//PULVERIZADOR,
	PULVERIZADOR_ACOPLADO(8,5),
	PULVERIZADOR_ARRASTO(8,5),
	PULVERIZADOR_CANHAO(8,5),
	PULVERIZADOR_COSTAL(5,0),
	PULVERIZADOR_HIDRAULICO(8,5),
	PULVERIZADOR_MANUAL(5,0),
	PULVERIZADOR_REBOCADO(8,5),
	PULVERIZADOR_TRACIONADO(8,5),
	PULVERIZADOR_TURBINA_FRUTICULTURA(8,5),
	PULVERIZADOR_TURBO_ATOMIZADOR(8,5),
	PULVERIZADORA_CANHAO(8,5),
	RASTELO_CAFE(3,0),
	RECOLHEDORA_CAFE(10,25),
	ROÇADEIRA(12,5),
	ROÇADEIRA_ARRASTO(12,5),
	ROÇADEIRA_HIDRAULICA(12,5),
	ROÇADEIRA_LATERAL(12,5),
	SOPRADOR_TRASEIRO_CAFE(5,5),
	SUBSOLADOR(15,5),
	SULCADOR(15,5),
	SULCADOR_ADUBADOR(15,5),
	SULCADOR_ADUBADOR_ABRIDOR_SULCO(15,5),
	SULCADOR_ADUBADOR_CANAVIEIRO(15,5),
	SULCADOR_CANAVIEIRO(15,5),
	SULCADOR_TANDEM_CAFE(15,5),
	TRITURADOR_CITROS_CAFE(12,5);
	
	private final int valor;

	private final double valorResidual;
	 
    private TipoAuxiliarMaquinas(int valor, double valorResidual) {
        this.valor = valor;
		this.valorResidual = valorResidual;
    }

    public int getValor() {
        return this.valor;
    }

	public double getValorResidual() {
        return this.valorResidual;
    }

	
}
